//
//  LoginModels.swift
//  Prelo
//
//  Created by Fachri Work on 11/13/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
    // MARK: Use cases
    
    enum User {
        
        struct Request {
            var emailUsername: String
            var password: String
        }
        
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    
    enum Error {
        
        struct Response {
            var message: String = ""
        }
        
        struct ViewModel {
            var message: String = ""
        }
    }
}
