//
//  LoginRouter.swift
//  Prelo
//
//  Created by Fachri Work on 11/13/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    func routeToLovelist(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Routing
    
    func routeToLovelist(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! LovelistViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToLovelist(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "LovelistViewController") as! LovelistViewController
            navigateToLovelist(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToLovelist(source: LoginViewController, destination: LovelistViewController) {
        source.navigationController?.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    func passDataToLovelist(source: LoginDataStore, destination: inout LovelistDataStore) {
        //destination.name = source.name
    }
}
