//
//  LoginWorker.swift
//  Prelo
//
//  Created by Fachri Work on 11/13/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import SwiftyJSON
import Alamofire
import UIKit

class LoginWorker {
    typealias LoginHandler = (ApiResponse.LoginResponse)->Void
    
    func login(_ request: Login.User.Request, completionHandler: @escaping LoginHandler)
    {
        
        let parameters: Parameters = ["username_or_email": request.emailUsername,
                                      "password": request.password]
        
        Alamofire.request(ApiConstants.absoluteUrl(path: ApiConstants.login),
                          method: .post,
                          parameters: parameters,
                          encoding: JSONEncoding.default,
                          headers: nil).responseJSON
            { (response) in
                
                if let jsonValue = response.result.value {
                    
                    let json = JSON(jsonValue)
                    
                    if let _message = json["_message"].string {
                        completionHandler(.error(message: _message))
                        return
                    }
                    
                    if let token = json["_data"]["token"].string {
                        completionHandler(.success(token: token))
                        return
                    }
                }
                    
                else {
                    completionHandler(.error(message: "Login Failed"))
                }
        }
    }
}
