//
//  LovelistInteractor.swift
//  Prelo
//
//  Created by Fachri Work on 11/13/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LovelistBusinessLogic {
    func lovelist()
}

protocol LovelistDataStore {
    //var name: String { get set }
}

class LovelistInteractor: LovelistBusinessLogic, LovelistDataStore {
    var presenter: LovelistPresentationLogic?
    var worker = LovelistWorker()
    //var name: String = ""
    
    // MARK: Do something
    
    func lovelist() {
        worker.lovelist() {response in
            
            switch response {
            case .success(let products):
                let response = Lovelist.Products.Response(products: products)
                self.presenter?.presentLovelist(response: response)
            case .error(let message):
                let response = Lovelist.Error.Response(message: message)
                self.presenter?.presentLovelistError(response: response)
            }
        }
        
    }
}
