//
//  LovelistPresenter.swift
//  Prelo
//
//  Created by Fachri Work on 11/13/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LovelistPresentationLogic {
  func presentSomething(response: Lovelist.Something.Response)
}

class LovelistPresenter: LovelistPresentationLogic {
  weak var viewController: LovelistDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Lovelist.Something.Response) {
    let viewModel = Lovelist.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
