//
//  LovelistInteractor.swift
//  Prelo
//
//  Created by Fachri Work on 11/13/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LovelistBusinessLogic {
  func doSomething(request: Lovelist.Something.Request)
}

protocol LovelistDataStore {
  //var name: String { get set }
}

class LovelistInteractor: LovelistBusinessLogic, LovelistDataStore {
  var presenter: LovelistPresentationLogic?
  var worker: LovelistWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Lovelist.Something.Request) {
    worker = LovelistWorker()
    worker?.doSomeWork()
    
    let response = Lovelist.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
