//
//  LovelistViewController.swift
//  Prelo
//
//  Created by Fachri Work on 11/13/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LovelistDisplayLogic: class {
    func displaySomething(viewModel: Lovelist.Something.ViewModel)
}

class LovelistViewController: UIViewController, LovelistDisplayLogic {
    var interactor: LovelistBusinessLogic?
    var router: (NSObjectProtocol & LovelistRoutingLogic & LovelistDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = LovelistInteractor()
        let presenter = LovelistPresenter()
        let router = LovelistRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    func setupNavigationBar() {
        if let navigationBar = navigationController?.navigationBar {
            navigationBar.isHidden = false
        }
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationController?.isNavigationBarHidden = false
        setupNavigationBar()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.setNavigationBarHidden(false, animated: animated)
    }
    
    // MARK: Do something
    
    @IBAction func logoutAction(_ sender: Any) {
        CacheManager.shared.token = ""
        self.navigationController?.popViewController(animated: true)
    }
    
    func doSomething() {
        let request = Lovelist.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: Lovelist.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
