//
//  LovelistPresenter.swift
//  Prelo
//
//  Created by Fachri Work on 11/13/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LovelistPresentationLogic {
    func presentLovelist(response: Lovelist.Products.Response)
    func presentLovelistError(response: Lovelist.Error.Response)
}

class LovelistPresenter: LovelistPresentationLogic {
    weak var viewController: LovelistDisplayLogic?
    
    // MARK: Do something
    
    func presentLovelist(response: Lovelist.Products.Response) {
        let viewModel = Lovelist.Products.ViewModel(products: response.products)
        viewController?.displayLovelist(viewModel: viewModel)
    }
    
    func presentLovelistError(response: Lovelist.Error.Response) {
        let viewModel = Lovelist.Error.ViewModel(message: response.message)
        viewController?.displayLovelistError(viewModel: viewModel)
    }
}
