//
//  LovelistModels.swift
//  Prelo
//
//  Created by Fachri Work on 11/13/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Lovelist {
    // MARK: Use cases
    
    enum Products {
        
        struct Request {
            
        }
        
        struct Response {
            var products : [Product]
        }
        
        struct ViewModel {
            var products : [Product]
        }
    }
    
    enum Error {
        
        struct Response {
            var message: String = ""
        }
        
        struct ViewModel {
            var message: String = ""
        }
    }
}
